name: eo-pv-cv
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - annotated-types
  - ca-certificates
  - curl
  - fsspec
  - gdal
  - geos
  # - h3pandas
  - pip
  - python=3.12.*
  - python-dateutilm
  # - requests
  # - rsgislib
  - pip:
      # - anywidget
      - contextily
      - cubo
      # - data-gradients
      - dask
      - datahugger
      # - dbt-core
      # - dbt-duckdb
      - duckdb>=1.2.0
      - duckdb-engine
      # - esda
      # - emoji
      - folium
      - fiona
      - geodatasets
      - geoarrow-pyarrow
      - geoarrow-pandas
      - geopandas
      # - geopy
      - earthengine-api
      - h3-py
      - imagecodecs # needed for tfrecord conversion -> (tiff, png mask)
      - ipyleaflet
      - ipython
      - ipywidgets
      - jupysql~=0.11
      - jupyterlab
      # - jupyter_bbox_widget
      # - jupyterlab_widgets
      # - jupyter_copilot
      # - jupyterlab-git
      # - jupyterlab-spreadsheet
      - lightning
      - lonboard
      - matplotlib
      - numpy
      # - onnx
      - opencv-python
      - openeo
      - overturemaps
      - pillow
      - planetary-computer
      - pvlib
      # - pretrainedmodels
      - pycountry
      - pydeck
      - pygeohash
      - pystac
      - pystac-client
      - rasterio
      - rastervision
      - rioxarray
      - rtree
      - sciencebasepy
      - scikit-image
      - scikit-learn
      - scipy
      - seaborn
      - seedir
      - segmentation-models-pytorch~=0.5
      - shapely
      - stac-geoparquet
      - stackstac
      # - terratorch
      # - super-gradients==3.7.1
      - tensorflow # need for handling tfrecords
      - tifffile
      - timm
      - tqdm
      - torch>=2.0.0
      - torchgeo~=0.7
      - torchmetrics>=1.0.0
      - torchvision
      - urllib3
      - wandb
      - xarray
      - yaml
# prefix: ~/miniforge3/envs/eo-pv-cv/
