name: eo-pv-cv
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - annotated-types
  - anywidget
  - ca-certificates
  - contextily
  - cpython>=3.10
  - cubo
  - curl
  - dask
  - esda
  - folium
  - fsspec
  - gdal
  - geopandas
  - geopy
  - geos
  - h3-py
  - h3pandas
  - ipyleaflet
  - ipython
  - ipywidgets
  - jupyterlab
  # - lightning
  # - lightning-utilities
  - lonboard
  - matplotlib
  # - networkx
  - notebook
  - overturemaps
  - pandas
  - pip
  - planetary-computer
  - pvlib
  - pydeck
  - pystac-client
  - python=3.12.*
  - python-dateutil
  - python-dotenv
  - pytorch-lightning
  - rasterio
  # - requests
  - rioxarray
  # - rsgislib
  - scikit-learn
  - shapely
  - stackstac
  - tqdm
  - urllib3
  - xarray
  - yaml
  - pip:
      - geoarrow-pyarrow
      # - geoarrow-pandas
      - albumentations
      # - data-gradients
      - datahugger
      - dbt-core
      - dbt-duckdb
      - duckdb>=1.2.0
      - duckdb-engine
      # - emoji
      - fiona
      - future
      - jupysql~=0.11
      - numpy
      # - onnx
      - opencv-python
      - openeo
      - pillow
      # - pip-tools
      # - pretrainedmodels
      - pycountry
      - pygeohash
      - pystac
      - rastervision
      - rtree
      # - s3transfer
      # - safetensors
      - sciencebasepy
      - scikit-image
      - scipy
      # - scisort
      # - scitree
      - seaborn
      - seedir
      - segmentation-models-pytorch
      - stac-geoparquet
      # - super-gradients==3.7.1
      # - tensorboard
      - tifffile
      - timm
      - torch>=2.0.0
      - torchgeo~=0.7
      - torchmetrics>=1.0.0
      - torchvision
# prefix: ~/miniconda3/envs/eo-pv-cv
