name: eo-pv-cv
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - overturemaps
  # narrow down geospatial viz libraries to avoid unnecessary dependencies
  # - cartopy
  - affine
  - annotated-types
  - anyio
  - anywidget
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arro3-compute
  - arro3-core
  - arro3-io
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - bleach-with-css
  - blosc
  - boost-cpp
  - bottleneck
  - branca
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - comm
  - contextily
  - contourpy
  - cpython>=3.10
  - cubo
  - curl
  - cycler
  - cyrus-sasl
  - dask-core
  - debugpy
  - decorator
  - defusedxml
  - deprecated
  - esda
  - exceptiongroup
  - executing
  - expat
  - filelock
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freetype
  - freexl
  - fsspec
  - gdal
  - geographiclib
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - geotiff
  - gettext
  - gettext-tools
  - giflib
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - gsl
  - h11
  - h2
  - h5py
  - hdf4
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipyleaflet
  - ipython
  - ipython_genutils
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json-c
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_leaflet
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libasprintf
  - libasprintf-devel
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgdal
  - libgettextpo
  - libgettextpo-devel
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libintl
  - libintl-devel
  - libkml
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libprotobuf
  - libpysal
  - librttopo
  - libsodium
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libtorch
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - lightning
  - lightning-utilities
  - llvm-openmp
  - locket
  - lonboard
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mercantile
  - minizip
  - mistune
  - mpc
  - mpfr
  - mpmath
  - muparser
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numexpr
  - openjpeg
  - openldap
  - openssl
  - opentelemetry-api
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - partd
  - pcre2
  - pexpect
  - pickleshare
  - pip
  - pixman
  - pkgutil-resolve-name
  - planetary-computer
  - platformdirs
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - psutil
  - psygnal
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pvlib
  - pycparser
  - pydantic
  - pydantic-core
  - pydeck
  - pygments
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyogrio
  - pyparsing
  - pyproj
  - pysocks
  - pystac-client
  - python=3.10.*
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch-lightning
  - pytz
  - pyyaml
  - pyzmq
  - qhull
  - rasterio
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rios
  - rpds-py
  - rsgislib
  - scikit-learn
  - send2trash
  - setuptools
  - shapely
  - six
  - sleef
  - sniffio
  - snuggs
  - soupsieve
  - sqlite
  - stack_data
  - stackstac
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - traittypes
  - types-python-dateutil
  - typing-extensions
  - typing-inspection
  - typing_extensions
  - typing_utils
  - tzcode
  - tzdata
  - unicodedata2
  - uri-template
  - uriparser
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - wrapt
  - xarray
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      # - geoarrow-pyarrow
      # - geoarrow-pandas
      # - stac-geoparquet
      
      - absl-py
      - aenum
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - alabaster
      - albucore
      - albumentations
      - antlr4-python3-runtime
      - arabic-reshaper
      - asn1crypto
      - async-timeout
      - boto3
      - botocore
      - build
      - cattrs
      - coloredlogs
      - configobj
      - coverage
      - cryptography
      - cssselect2
      - cython
      - data-gradients
      - datahugger
      - dbt-core
      - dbt-duckdb
      - docstring-parser
      - docutils
      - duckdb>=1.9.0
      - efficientnet-pytorch
      - emoji
      - einops
      - everett
      - fiona
      - flatbuffers
      - frozenlist
      - future
      - gitignorefile
      # - GitPython>=3.1.2
      - grpcio
      - html5lib
      - huggingface-hub
      - humanfriendly
      - humanize
      - hydra-core
      - imagededup
      - imageio
      - imagesize
      - iniconfig
      - jmespath
      - json-tricks
      - jsonargparse
      - jsonpath-ng
      - kornia
      - kornia-rs
      - lazy-loader
      - lightly
      - lightly-utils
      - lxml
      - markdown
      - markdown-it-py
      - mdurl
      - multidict
      - munch
      - natsort
      - numpy>=1.23.0
      - omegaconf
      - onnx
      - onnxruntime
      - onnxsim
      - opencv-python
      - opencv-python-headless
      - openeo
      - oscrypto
      - pillow
      - pip-tools
      - pluggy
      - ply
      - pretrainedmodels
      - progress
      - propcache
      - protobuf>=3.20.0
      - pycocotools
      - pydeprecate
      - pygeohash
      - pyhanko
      - pyhanko-certvalidator
      - pypdf
      - pyproject-hooks
      - pystac
      - pytest
      - python-bidi
      - pywavelets
      - qrcode
      - qudida
      - rapidfuzz
      - rastervision
      - rastervision-aws-batch
      - rastervision-aws-s3
      - rastervision-core
      - rastervision-pipeline
      - rastervision-pytorch-backend
      - rastervision-pytorch-learner
      - reportlab
      - requests-cache
      - requests-mock
      - rich
      - rtree
      - s3transfer
      - safetensors
      - sciencebasepy
      - scikit-image
      - scipy
      - scisort
      - scitree
      - seaborn
      - seedir
      - segmentation-models-pytorch
      - simsimd
      - snowballstemmer
      - sphinx
      - sphinx-rtd-theme
      - sphinxcontrib-applehelp
      - sphinxcontrib-devhelp
      - sphinxcontrib-htmlhelp
      - sphinxcontrib-jquery
      - sphinxcontrib-jsmath
      - sphinxcontrib-qthelp
      - sphinxcontrib-serializinghtml
      - stringcase
      - stringzilla
      # - super-gradients==3.7.1
      - svglib
      - sympy
      - tensorboard
      - termcolor
      - tifffile
      - timm
      - torch>=2.0.0
      - torchgeo
      - torchmetrics>=1.0.0
      - torchvision
      - treelib
      - triangle
      - typeshed-client
      - tzlocal
      - uritools
      - url-normalize
      - werkzeug
      - xhtml2pdf
      - yarl
# prefix: ~/miniconda3/envs/eo-pv-cv
